"""add_partner_api_credentials_and_stats

Revision ID: ce22f3383b79
Revises: 001_initial
Create Date: 2026-01-16 19:19:12.357994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce22f3383b79'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    op.add_column('partner', sa.Column('api_key', sa.String(length=100), nullable=True, comment='Public API key (pk_live_...) for partner identification'))
    op.add_column('partner', sa.Column('secret_key', sa.String(length=128), nullable=True, comment='Private secret key (sk_live_...) for HMAC signatures - NEVER expose in responses'))
    op.add_column('partner', sa.Column('email', sa.String(length=255), nullable=True, comment='Partner contact email'))
    op.add_column('partner', sa.Column('webhooks_sent', sa.Integer(), nullable=False, server_default='0', comment='Total webhooks sent to this partner'))
    op.add_column('partner', sa.Column('webhooks_succeeded', sa.Integer(), nullable=False, server_default='0', comment='Webhooks successfully delivered (2xx response)'))
    op.add_column('partner', sa.Column('webhooks_failed', sa.Integer(), nullable=False, server_default='0', comment='Failed webhook deliveries (errors, timeouts, 5xx)'))
    op.add_column('partner', sa.Column('last_webhook_at', sa.TIMESTAMP(), nullable=True, comment='Timestamp of last webhook delivery attempt (UTC)'))
    
    # Generate values for existing rows
    op.execute("""
        UPDATE partner 
        SET api_key = 'pk_live_' || md5(random()::text || clock_timestamp()::text)::text,
            secret_key = 'sk_live_' || md5(random()::text || clock_timestamp()::text)::text
        WHERE api_key IS NULL
    """)
    
    # Now make columns NOT NULL
    op.alter_column('partner', 'api_key', nullable=False)
    op.alter_column('partner', 'secret_key', nullable=False)
    
    op.alter_column('partner', 'shared_secret',
               existing_type=sa.VARCHAR(length=128),
               comment='HMAC-SHA256 secret for webhook signature validation (deprecated - use secret_key)',
               existing_comment='HMAC-SHA256 secret for webhook signature validation',
               existing_nullable=False)
    op.create_index(op.f('ix_partner_api_key'), 'partner', ['api_key'], unique=True)
    op.drop_constraint('payment_external_payment_id_key', 'payment', type_='unique')
    op.create_index(op.f('ix_payment_provider_config_is_active'), 'payment_provider_config', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_provider_config_is_active'), table_name='payment_provider_config')
    op.create_unique_constraint('payment_external_payment_id_key', 'payment', ['external_payment_id'])
    op.drop_index(op.f('ix_partner_api_key'), table_name='partner')
    op.alter_column('partner', 'shared_secret',
               existing_type=sa.VARCHAR(length=128),
               comment='HMAC-SHA256 secret for webhook signature validation',
               existing_comment='HMAC-SHA256 secret for webhook signature validation (deprecated - use secret_key)',
               existing_nullable=False)
    op.drop_column('partner', 'last_webhook_at')
    op.drop_column('partner', 'webhooks_failed')
    op.drop_column('partner', 'webhooks_succeeded')
    op.drop_column('partner', 'webhooks_sent')
    op.drop_column('partner', 'email')
    op.drop_column('partner', 'secret_key')
    op.drop_column('partner', 'api_key')
    # ### end Alembic commands ###